/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p10;

import java.awt.Color;
import sm.cag.iu.Lienzo2DImagen;

/**
 *
 * @author PC
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    
    VentanaPrincipal parent = null;

    
    /**
     * Creates new form VentanaInterna
     * @param parent
     */
    public VentanaInterna(VentanaPrincipal parent) {
        initComponents();
        this.parent = parent;
        this.lienzo2DImagen2.setBackground(Color.white);
    }
    
    public Lienzo2DImagen getLienzo(){
        return this.lienzo2DImagen2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2DImagen2 = new sm.cag.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo");
        setToolTipText("");

        javax.swing.GroupLayout lienzo2DImagen2Layout = new javax.swing.GroupLayout(lienzo2DImagen2);
        lienzo2DImagen2.setLayout(lienzo2DImagen2Layout);
        lienzo2DImagen2Layout.setHorizontalGroup(
            lienzo2DImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );
        lienzo2DImagen2Layout.setVerticalGroup(
            lienzo2DImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2DImagen2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.cag.iu.Lienzo2DImagen lienzo2DImagen2;
    // End of variables declaration//GEN-END:variables
}
