/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import com.github.sarxos.webcam.Webcam;
import java.awt.image.BufferedImage;

/**
 *
 * @author CArlos
 */
public class VentanaInternaSM extends javax.swing.JInternalFrame {
    VentanaPrincipal parent = null;

    /**
     * Creates new form VentanaInternaSM
     */
    public VentanaInternaSM() {
        initComponents();
    }
    
    public BufferedImage getImage(){
        return null;
    }
    
    public BufferedImage getShot(){
        return null;
    }
    
    public Webcam getCamara(){
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
